### PR TITLE
Add option to toogle minify on HTML

### PR DESCRIPTION
**Pull request by macaoidh**
I added an option to toggle HTML minifying. Default behaviour of your plugging has not been changed. Would you be kind to merge my changes into your project?

Thank you very much.

Eric Mc Kay

### CODE REVIEW

**Comment by anseki** [comment]
Hi macaoidh, thank you for your PR.

Sorry but, I can't understand the meaning of this option.
It seems that, when this option is enabled, there are not work htmlclean do.
What is this for?

**Comment by macaoidh** [comment]
Hi Anseki,

Thanks for your rapid answer!

From my perspective, your module does two different things:
- Remove all the comments in HTML
- Minify the HTML
That's why I like your name: htmlclean. It's not minifyHTML or RemoveCommentsHTML. It does both!

Howevwer, in some situations, I need to remove comments in HTML wihtout minifying HTML. I tried different "Remove comment HTML Tools", but I found that your module does the job perfectly, by protecting some important comments, like SSI. 

So, because I found that you have done a really good job with the removing comment part, I am asking you if you can add an option that toogle the minifying in the core module.

Eric Mc Kay

**Comment by anseki** [comment]
I see.
Sorry but, I can't merge this PR.

- htmlclean is HTML cleaner to minify by doing various things. That includes adjusting attributes, reducing whitespaces, removing HTML/SVG comments, and others. Those are included in the work to minify. That is, the "Minify" of which you call includes removing HTML comments. Since many users think so, they will interpret this option as saying to the module to minify, "don't minify". (It means that it force the module not to work.) For example, this option should be named like `onlyComments` (reversed boolean).

- PRs should follow coding styles of target, such as indent. htmlclean employs 2 spaces indent.

- If you want to remove HTML comments, you can do it very easily by just one RegExp like `/<\s*\!\s*--[\s\S]*?--\s*>/`. You don't need htmlclean.

- I can't understand some codes in your PR.
Does `options.minify !== 'undefined'` mean `typeof options.minify !== 'undefined'`?
Does this code below:

```js
if (options && options.minify !== 'undefined') {
  minify = (typeof options.minify === 'boolean') ? options.minify : minify;
}
```

mean this?:

```js
if (options && typeof options.minify === 'boolean') {
  minify = options.minify;
}
```

(`boolean` is already not `undefined`.)

[This](https://github.com/anseki/htmlclean#see-also) might help you.

**Comment by macaoidh** [comment]
Hi Anseki,

I clearly understand what you mean. If the term "minify" implies that the module should remove comments, toggleling the variable "minify" have no sense in this contexte. I understand why you would not merge this options into the core module. I think that you are rigth when you are saying that naming the variable "onlyComments" is more semantic and less confusing.

Thanks for your advices, I appreciate your comments.

Thanks for your time,

Eric Mc Kay

**Pull request closed without merging**
